# Generated by Django 3.0.4 on 2020-04-16 12:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicStrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strip_image', models.ImageField(upload_to='Skribbly/Comic Strips/')),
                ('title', models.CharField(max_length=32)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=6)),
                ('email', models.EmailField(max_length=256)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)])),
                ('profile_picture', models.ImageField(upload_to='Skribbly/Profile Pictures/')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to='Skribbly.ComicStrip')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=512)),
                ('edited', models.BooleanField()),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('comic_strip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Skribbly.ComicStrip')),
                ('downvotes', models.ManyToManyField(blank=True, related_name='downvotes', to='Skribbly.User')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvotes', to='Skribbly.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Skribbly.User')),
            ],
        ),
        migrations.AddField(
            model_name='comicstrip',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='Skribbly.User'),
        ),
        migrations.AddField(
            model_name='comicstrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic_strips', to='Skribbly.User'),
        ),
    ]
