# Generated by Django 3.0.4 on 2020-04-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Skribbly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='age',
        ),
    ]
