# Generated by Django 3.0.4 on 2020-04-19 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Skribbly', '0002_remove_artist_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='age',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
